### PR TITLE
Update types 3

### PR DESCRIPTION
**Pull request by dessalines**
Updating types from main again.

### CODE REVIEW

**Comment by SleeplessOne1917** [comment]
With [the updated SSO types merged in the backend](https://github.com/LemmyNet/lemmy/pull/5046), I think you should update this PR to include the types that get generated from that. Since running the TS type generation script on main will generate the types in this PR as well, it's easier than having 2 separate ones.

**Comment by dessalines** [comment]
K, will do.

**Comment by dessalines** [comment]
These ones are still having issues: 

`auto_verify_email: boolean | null;`

I'll check it out.

**Comment by dessalines** [comment]
@matc-pub K `0.20.0-alpha.17` is building and should be done in a minute.

**Review by SleeplessOne1917 — APPROVED** [review]

**Pull request merged**
