### PR TITLE
Add option types

### PR DESCRIPTION
**Pull request by dessalines**
You can see all the boilerplate this adds. But at least we got serializeable option types.

### CODE REVIEW

**Review by Nutomic — APPROVED** [review]

**Comment by shilangyu** [comment]
Hi! May I ask what was the rational? I 100% agree that a monadic Option is much more safe, but I feel like the ergonomics and readability of these contracts plummeted. Was there a specific issue that was being fixed?

**Comment by dessalines** [comment]
Yep I apologize for all the added bloat, and the switched from simple interfaces to annotated classes. Agree it was **much** easier to read before. 

The reason to add this was so that lemmy-ui could have proper monadic option types, thus forcing compile-time null-pointer checks. It was a lot of work and boilerplate to add this, but it eliminated a whoe class of null-pointer-exception bugs in the UI code. Rust and Kotlin have compile-time NPE checking, but typescript doesn't natively without using some extra library like monads.

**Comment by shilangyu** [comment]
That is interesting, typescript does do compile-time null checks ([see here](https://www.typescriptlang.org/tsconfig#strictNullChecks)) and rejects code that does not conform to it. Nullables are represented as a union with `undefined` and/or `null`. Doesn't this result in a very similar end goal of no NPE? I personally did not have problems with typescripts way of enforcing null safety. I see in lemmy-ui you have disabled null-checks, I quickly enabled it locally to see what it would report, and it reported 1506 NPE errors. Perhaps you might even want to enable [`strict`](https://www.typescriptlang.org/tsconfig#strict) to get all checks typescript has to offer (which bumped up the error count to 1561). I hope this helps, I too am a type-safety lover :)

**Comment by dessalines** [comment]
I had no idea about that, nice. Might be worth it to enable it at some point, but it mostly looked liked it was just catching the states not being initialized. Monads / Option types are def superior to typescripts nulls tho, so there wouldn't be any value in going back now that the work is done.

**Pull request merged**
