### PR TITLE
Add enable_keyboard_navigation setting

### PR DESCRIPTION
**Pull request by HamzahMansour**
Needed for https://github.com/LemmyNet/lemmy-ui/pull/1892 and https://github.com/LemmyNet/lemmy/pull/3569

### CODE REVIEW

**Comment by SleeplessOne1917** [comment]
Does this need a setting? I don't see why this wouldn't always be on.

**Comment by HamzahMansour** [comment]
> Does this need a setting? I don't see why this wouldn't always be on.

1. I wouldn't want this to be on by default until it's much more refined and tested
2. it'll probably impact accessibility with overriding key presses and browser focus, styles, etc
3. adds complexity and no real explanation (yet) on how to use/configure it
4. not everyone wants this and I don't want to impose it on people that don't want to use it

Though I'd be okay with eventually setting this to always on if all of those issues are sorted out.

**Comment by SleeplessOne1917** [comment]
That makes sense. I was thinking more along the lines of when it was in its end state, but you're right that leaving this always on while it's still in the oven is ill advised.

**Review by SleeplessOne1917 — APPROVED** [review]

**Comment by dessalines** [comment]
This is added now in a newer PR.

**Pull request closed without merging**
